### ISSUE TITLE
Hi, i am a dev interested in this deploy

### ISSUE THREAD

**Issue by EFixPro** [Narwal25/saas-kit-odoo#1]
i'm getting this error: Odoo-SAAS-Data  common-addons_v15  common-addons_v16  common-addons_v17  dockerv15  dockerv16  dockerv17  webkul_addons
'/home/ubuntu/saas-files/docker_files-all/dockerv16/docker-data/' -> '/opt/odoo/odoo-17-saas-webkul/dockerv16/docker-data'
'/home/ubuntu/saas-files/docker_files-all/dockerv17/docker-data/' -> '/opt/odoo/odoo-17-saas-webkul/dockerv17/docker-data'
Copied Docker files
[+] Building 0.1s (1/1) FINISHED                                                                                                                                                                   docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                         0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                           0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory 

you have the docker files needed for this?

**Comment by narwal25** [comment]
This is not an issue with the script itself. The error you're encountering is likely due to missing the necessary Dockerfiles. As mentioned in the Readme.md, this script is a helper for installing the SaaS Kit for Odoo. You will need to purchase or obtain the SaaS Kit Odoo module files from a vendor such as Webkul Software Pvt. Ltd. Once you have those files, place them in the designated folder on your server and provide the correct path in the saas-files prompt.

Please ensure you've followed the setup instructions provided in the documentation.
